# Change these first
owner: b00nw33 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: td-streamlit on Streamlit
    url: https://td-str.streamlit.app
  - name: td-streamlit on Render
    url: https://td-streamlit.onrender.com
  - name: CF-Jekyll on Vercel
    url: https://cf-jekyll.vercel.app
  - name: CF-Jekyll on Github
    url: https://b00nw33.github.io/cf-jekyll
  - name: CF-Jekyll on CloudFlare
    url: https://cf-jekyll.pages.dev
  - name: CF-Svelte on CloudFlare
    url: https://cf-svelte-b98.pages.dev
  - name: CF-NextJS on CloudFlare
    url: https://cf-nextjs-014.pages.dev
  - name: CF-NextJS on Vercel
    url: https://cf-nextjs.vercel.app    
  - name: NextJS on Vercel
    url: https://td-nextjs.vercel.app
  - name: NextJS on Render
    url: https://td-nextjs.onrender.com
  - name: Flask on Vercel
    url: https://td-flask.vercel.app
  - name: Flask on Render
    url: https://td-flask.onrender.com
  # - name: Autopycaret on Streamlit
  #   url: https://autopycaret.streamlit.app
  # - name: Pycaret Test on Streamlit
  #   url: https://app-test-pycaret.streamlit.app
  # - name: Google
  #   url: https://www.google.com
  # - name: Wikipedia
  #   url: https://en.wikipedia.org
  # - name: Hacker News
  #   url: https://news.ycombinator.com
  # - name: Test Broken Site
  #   url: https://thissitedoesnotexist.koj.co
  # - name: IPv6 test
  #   url: forwardemail.net
  #   port: 80
  #   check: "tcp-ping"
  #   ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
